name:        pairing
version:     0.5.0
synopsis:    Bilinear pairings
description: Optimal Ate pairing over Barreto-Naehrig curves
maintainer:  Adjoint Inc (info@adjoint.io)
license:     MIT
github:      adjoint-io/pairing
category:    Cryptography

default-extensions:
  - LambdaCase
  - RecordWildCards
  - OverloadedStrings
  - NoImplicitPrelude
  - FlexibleInstances
  - FlexibleContexts
  - ScopedTypeVariables
  - RankNTypes
  - BangPatterns
  - DataKinds
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - PatternSynonyms
  - TypeApplications
  - TypeSynonymInstances

dependencies:
  - base >= 4.10 && < 5
  - protolude >= 0.2
  - bytestring
  - elliptic-curve >= 0.2 && < 0.3
  - errors
  - galois-field >= 0.4 && < 0.5
  - MonadRandom
  - QuickCheck
  - wl-pprint-text

extra-source-files:
  - README.md
  - ChangeLog.md

ghc-options:
  - -freverse-errors
  - -Wall

library:
  exposed-modules:
    - Pairing.Ate
    - Pairing.ByteRepr
    - Pairing.Curve
    - Pairing.Hash
    - Pairing.Serialize.Types
    - Pairing.Serialize.Jivsov
    - Pairing.Serialize.MCLWasm
  source-dirs:
    - src

tests:
  pairing-tests:
    main: Main
    dependencies:
      - quickcheck-instances
      - tasty
      - tasty-hunit
      - tasty-quickcheck
    source-dirs:
      - src
      - tests

benchmarks:
  pairing-benchmarks:
    main: Main
    dependencies:
      - criterion
      - QuickCheck
      - quickcheck-instances
      - tasty
      - tasty-hunit
      - tasty-quickcheck
    source-dirs:
      - src
      - benchmarks
