name:        pairing
version:     0.5.0
synopsis:    Bilinear pairings
description: Optimal Ate pairing over Barreto-Naehrig curves
maintainer:  Adjoint Inc (info@adjoint.io)
license:     MIT
github:      adjoint-io/pairing
category:    Cryptography

default-extensions:
  - LambdaCase
  - RecordWildCards
  - OverloadedStrings
  - NoImplicitPrelude
  - FlexibleInstances
  - FlexibleContexts
  - ScopedTypeVariables
  - RankNTypes
  - DataKinds
  - DeriveGeneric
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - PatternSynonyms
  - StandaloneDeriving
  - TypeFamilyDependencies

dependencies:
  - base >= 4.10 && < 5
  - protolude >= 0.2 && < 0.3
  - bytestring
  - elliptic-curve >= 0.2 && < 0.3
  - errors
  - galois-field >= 0.4 && < 0.5
  - groups
  - MonadRandom
  - poly
  - semirings
  - tasty-quickcheck
  - wl-pprint-text

extra-source-files:
  - README.md
  - ChangeLog.md

ghc-options:
  - -freverse-errors
  - -O2
  - -Wall

library:
  exposed-modules:
    - Data.Pairing
    - Data.Pairing.BN
    - Data.Pairing.BN.BN254
    - Data.Pairing.BN.BN254A
    - Data.Pairing.BN.BN254B
    - Data.Pairing.BN.BN462
    - Data.Pairing.BLS
    - Data.Pairing.BLS.BLS12381
    - Data.Pairing.BLS.BLS48581
  other-modules:
    - Data.Pairing.BN.Ate
    - Data.Pairing.BN.Base
    - Data.Pairing.BN.BN254.Base
    - Data.Pairing.BN.BN254.Byte
    - Data.Pairing.BN.BN254.Hash
    - Data.Pairing.BN.BN254.Serialize.Jivsov
    - Data.Pairing.BN.BN254.Serialize.MCLWasm
    - Data.Pairing.BN.BN254.Serialize.Types
    - Data.Pairing.BN.BN254A.Base
    - Data.Pairing.BN.BN254B.Base
    - Data.Pairing.BN.BN462.Base
    - Data.Pairing.BLS.BLS12381.Ate
    - Data.Pairing.BLS.BLS12381.Base
    - Data.Pairing.BLS.BLS12381.Hash
    - Data.Pairing.BLS.BLS48581.Base
    - Data.Pairing.Byte
  source-dirs:
    - src

tests:
  pairing-tests:
    main: Main
    dependencies:
      - pairing
      - QuickCheck
      - quickcheck-instances
      - tasty
      - tasty-hunit
      - tasty-quickcheck
    source-dirs:
      - test

benchmarks:
  pairing-benchmarks:
    main: Main
    dependencies:
      - criterion
      - pairing
      - QuickCheck
      - quickcheck-instances
      - tasty
      - tasty-hunit
      - tasty-quickcheck
    source-dirs:
      - bench
