name: pairing
version: 0.1.1
synopsis: Optimal ate pairing over Barreto-Naehrig curves
description: Optimal ate pairing over Barreto-Naehrig curves
maintainer: Adjoint Inc (info@adjoint.io)
license: MIT
github: adjoint-io/pairing
category: Cryptography

extra-source-files:
- README.md
- ChangeLog.md

flags:
  static:
    description: Emit statically-linked binary
    manual: False
    default: False

  optimized:
    description: Perform compiler optimizations
    manual: False
    default: False

dependencies:
  # Prelude
  - base >= 4.7 && < 5
  - protolude  >= 0.2
  - cryptonite
  - bytestring
  - random
  - memory
  - wl-pprint-text
  - QuickCheck

library:
  source-dirs: src

  ghc-options:
    -fwarn-tabs
    -fwarn-incomplete-patterns
    -fwarn-incomplete-record-updates
    -fwarn-redundant-constraints
    -fwarn-implicit-prelude
    -fwarn-overflowed-literals
    -fwarn-orphans
    -fwarn-identities
    -fwarn-dodgy-exports
    -fwarn-dodgy-imports
    -fwarn-duplicate-exports
    -fwarn-overlapping-patterns
    -fwarn-missing-fields
    -fwarn-missing-methods
    -fwarn-missing-signatures
    -fwarn-noncanonical-monad-instances
    -fwarn-unused-pattern-binds
    -fwarn-unused-type-patterns
    -fwarn-unrecognised-pragmas
    -fwarn-wrong-do-bind
    -fno-warn-name-shadowing
    -fno-warn-unused-binds
    -fno-warn-unused-matches
    -fno-warn-unused-do-bind

  default-extensions:
    - LambdaCase
    - RecordWildCards
    - OverloadedStrings
    - NoImplicitPrelude
    - FlexibleInstances

  exposed-modules:
    - Pairing.Params
    - Pairing.Fq
    - Pairing.Fr
    - Pairing.Fq2
    - Pairing.Fq6
    - Pairing.Fq12
    - Pairing.Point
    - Pairing.Group
    - Pairing.Pairing
    - Pairing.Jacobian

tests:
  test-circuit-compiler:
    main: Driver.hs
    source-dirs: tests
    dependencies:
      - pairing
      - base
      - tasty
      - tasty-discover
      - tasty-hunit
      - tasty-quickcheck
      - QuickCheck

benchmarks:
  pairing-benchmarks:
    main: Main.hs
    source-dirs: bench, tests
    other-modules:
      - BenchPairing
    dependencies:
      - pairing
      - criterion
      - QuickCheck
      - tasty
      - tasty-quickcheck
      - tasty-hunit
