resolver: lts-13.19
extra-deps:
  - semirings-0.5
  - git: https://github.com/adjoint-io/elliptic-curve.git
    commit: f27eba1c3a39b9a11c1bb60ea837fbce74025388
  - git: https://github.com/adjoint-io/galois-field.git
    commit: 2ae316d0a39130cfed44b8dc314755d8e1310051
  - git: https://github.com/adjoint-io/poly.git
    commit: 1eb5b7a820a685de7c07576e028dee332e3382f8
