resolver: lts-13.19
extra-deps:
  - git: https://github.com/adjoint-io/galois-field.git
    commit: e996bde4f009f01608bffd8fd4da8ef2c6af24d4
  - git: https://github.com/adjoint-io/elliptic-curve.git
    commit: cdcae8402e37f2a2c88aa5e8d825e98d0c29f60a
  - git: https://github.com/chessai/semirings.git
    commit: 8b6c208f3d771fae066fcb637da492e7251a8e50
  - git: https://github.com/adjoint-io/poly.git
    commit: 1eb5b7a820a685de7c07576e028dee332e3382f8
